### PR TITLE
Better installation setup

### PR DESCRIPTION
**Pull request by natir**
Hello,

We try to install munin and I detect some failure.

This commit solved it.

Thanks, for your work

Regards

### CODE REVIEW

**Comment by Aluriak** [comment]
Please remove lines about virtualenv in the README file ; these informations are not relevant.

**Comment by natir** [comment]
It's your project, masterrrrrrrrrr

**Comment by Aluriak** [comment]
You can keep the .gitignore line, however.
Note that _venv_ is already present.

**Comment by natir** [comment]
I wait you accept this PR for create another PR about gitignore

**Pull request merged**
